# Configuración del plugin
messages:
  welcome_message:
    enabled: true
    message: "Bienvenido al server!, %player%!"
  death_message:
    enabled: true
    title: "MUERTE!"
    subtitle: "%player% ha muerto!"
  ban_message:
    enabled: true
    message: "Has sido permabaneado del server!"

config:
  kick_if_ip_changed: true
  storm_time: 10

  tablist:
    header: "&6Bienvenido a Death Scape, %player%!"
    footer: "&eJugadores en línea: &a%online_players%"
