# Configuración del plugin
messages:
  welcome_message:
    enabled: true
    message: "Bienvenido al server %player%!"
  death_message:
    enabled: true
    title: "MUERTE!"
    subtitle: "%player% ha muerto!"
  ban_message:
    enabled: true
    message: "Has sido permabaneado del server!"
  totem_success: "&a¡El tótem te ha salvado con una probabilidad de &b{randomValue}&f/&c{successProbability}&a!"
  totem_failure: "&cEl jugador &a{playerName} &cusó un tótem con probabilidad &4{randomValue}&f/&9{successProbability}"
  totem_broadcast_success: "&a¡El jugador &b{playerName} &aha sobrevivido gracias a su tótem con una probabilidad de &b{randomValue}&f/&c{successProbability}&a!"
config:
  kick_if_ip_changed: true
  storm_time: 10
  points_to_reduce_on_death: 5
  totem_success_probability: 50
groups:
  owner:
    prefix: "&4[Owner]"
    permissions:
      - "ban"
      - "kick"
      - "teleport"
      - "reload"
      - "reports"
      - "fly"
      - "chat"
      - "heal"
    players:
      - "xaviggr"
      - "4gymo"
      - "gery345"
      - "link"
  default:
    prefix: "&7[User]"
    permissions:
    players:
