main: dc.DeathScape
version: 1.0.0
name: DeathScape
author: xaviggr
api-version: 1.20
folia-supported: true

commands:
  Deathscape:
    description: DeathScape main command
    usage: /<command>
    aliases: [ds]